version: '3.8'

services:
  spark-master:
    image: fed-spark-node
    volume:
      - ./app:/app
    environment:
      - SPARK_MODE=master
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - spark-net
    mem_limit: 3g
    cpus: 2

  spark-worker:
    image: fed-spark-node
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-net
    deploy:
      replicas: 10
    mem_limit: 3g
    cpus: 2

networks:
  spark-net:
    driver: bridge
